server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  packageToScan: Owing

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/owing
    username: ${postgres-username}
    password: ${postgres-password}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    neo4j:
      uri: bolt://localhost:7687
      authentication:
        username: ${neo4j-username}
        password: ${neo4j-password}

  redis:
    host: localhost
    port: 6379
    timeout: 5000

  application:
    name: spring-ai

  ai:
    openai:
      api-key: ${api-key}
      chat:
        options:
          model: gpt-4o